version: "2.4"
services:
  app:
    container_name: "application-server"
    image: us-central1-docker.pkg.dev/terra-vdevel-fast-leek-3335/applications/workbench
    restart: always
    volumes:
      - ..:/workspace:cached
      - work:/home/workbench
    ports:
      - 3000:3000
      - 3002:3002
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
networks:
  app-network:
    external: true
volumes:
  work:
